version: '3'
services:
  web:
    build: ./nginx
    ports:
      - 8080:80
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./src:/var/www/html
    depends_on:
      - app
    links:
      - app

  app:
    build: ./php
    volumes:
      - ./src:/var/www/html
    depends_on:
      - db
    links:
      - db

  db:
    image: mysql:latest
    ports:
      - 13306:3306
    volumes:
      - ./mysql/data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: secret